name: tdiblik/corsproxy
services:
  proxy:
    image: "nginx:alpine"
    hostname: "corsproxy"
    restart: no
    ports:
      - "1337:80"
    environment:
      - NGINX_PORT=80
      - CORS_TARGET=host.docker.internal
      - CORS_TARGET_PORT=8080
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
    command: [nginx-debug, "-g", "daemon off;"]
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
